### PR TITLE
Feat add verbosity levels

### PR DESCRIPTION
**Pull request by guiferrpereira**
screen shot 2016-11-23 at 16 23 17

This fix all console.logs and console.warn that this js have.

There are 3 levels of verbosity:

- **errors** : disables console.log and console.warn
- **warnings**: disables console.log
- **debug**: don't disable anything

Should be used on initializer as:
`PdfjsViewer.verbosity = ENV['PDFJS_VIEWER_VERBOSITY']`

### CODE REVIEW

**Review by urkle — CHANGES_REQUESTED** [review]
do an interactive rebase that REMOVED the moz response type commit from this branch/PR

**Comment by guiferrpereira** [comment]
> do an interactive rebase that REMOVED the moz response type commit from this branch/PR

done @urkle

**Comment by urkle** [comment]
um..  why is this even needed?  It also looks rather hacky for overwriting the window.console object.

**Comment by guiferrpereira** [comment]
No it's not needed, i can remove that default. I try to replicate what they have done with HOSTED_VIEWER_ORIGINS :)

**Comment by urkle** [comment]
I just don't think we need to make this change at all.  The average user isn't going to see these messages anyways.. And they are helpful for diagnosing issue when we do have them.

**Pull request closed without merging**
